default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV['DB_POOL'] || ENV['MAX_THREADS'] || 5 %>
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  database: slack-lock-bot_development

test:
  <<: *default
  database: slack-lock-bot_test

production:
  <<: *default
